server:
  port: 8080
spring:
  application:
    name: accounts
  data:
    mongodb:
      database: diciembre
      uri: mongodb+srv://ramos10:j9Po6zMuZ0A9cb1F@cluster0-dkhur.mongodb.net/diciembre?retryWrites=true&w=majority